modul_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('store.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from store.views import *


urlpatterns = [
    path('', SnusListView.as_view(), name='index'),
    path('login/', Login.as_view(), name='login'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('logout/', Logout.as_view(), name='logout'),
    path('snus/create/', SnusCreateView.as_view(), name='snus_create'),
    path('snus/update/<int:pk>', UpdateSnusView.as_view(), name='update'),
    path('snus/purchase/<int:pk>', PurchaseSnusView.as_view(), name='purchase'),
    path('snus/purchase_list', PurchasesListView.as_view(), name='purchase_list'),
    path('snus/purchase_return/<int:pk>', ReturnSnusView.as_view(), name='return_snus'),
    path('snus/returns_list', ReturnsListView.as_view(), name='returns'),
    path('snus/delete_return/<int:pk>', DeclineReturnView.as_view(), name='decline_return'),
    path('snus/accept_return/<int:pk>', AcceptReturnView.as_view(), name='accept_return'),

]

store/models.py
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from datetime import datetime, timedelta

Gender = ((1, 'Man'),
              (2, 'Woman'))
English = ((1, 'A1'),
               (2, 'A2'),
               (3, 'B1'),
               (4, 'B2'),
               (5, 'C1'),
               (6, 'C2'),)

# Create your models here.
class StoreUser(AbstractUser):
    UserWallet = models.PositiveIntegerField(default=10000)

    def __str__(self):
        return "{}".format(self.username)


class Snus(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    picture = models.ImageField(upload_to='media', default='default.jpg', blank=True, null=True)
    price = models.PositiveIntegerField(default=0)
    quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return "{}".format(self.title)


class Purchase(models.Model):
    customer = models.ForeignKey(StoreUser, on_delete=models.CASCADE)
    product = models.ForeignKey(Snus, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    purchase_time = models.DateTimeField(auto_now_add=True )

    def __str__(self):
        return "{} from {} ".format(self.product, self.customer)


class ReturnPurchase(models.Model):
     purchase_return = models.ForeignKey(Purchase, on_delete=models.CASCADE)
     time_of_return =models.DateTimeField(auto_now_add=True)

     def __str__(self):
         return "{} wanted to return at {}".format(self.purchase_return, self.time_of_return)


class ModelSerial(models.Model):
    name = models.CharField(max_length=100)
    gender = models.CharField(choices=Gender, max_length=100)
    age = models.IntegerField()
    english_lvl = models.CharField(choices=English, max_length=100)

    def clean(self):
        cleaned_data = super().clean()
        age = cleaned_data.get('age')
        gender = cleaned_data.get('gender')
        english_lvl = cleaned_data.get('english_lvl')

        if not (gender == '1' and age >= 20 and int(english_lvl) >= 4) and not \
                (gender == '2' and age >= 22 and int(english_lvl) >= 3):
            raise ValidationError('Sorry you cant work with us')

templates/index.html
{% extends 'main.html' %}

{% block content %}
    <h1 style=" background-color: aqua" >My modul Store</h1>
  {% if request.user.is_authenticated and not request.user.is_superuser %}
        <a href="{% url 'logout' %}">Logout</a>
      <br>
      <br>
        <a href="{% url 'purchase_list' %}"> My purchases</a>
      <br>
      <br>

      <span style="background-color: lightblue">User: {{ request.user.username }} </span>
      <br>

        <span style="background-color: yellow"> Your wallet: {{ request.user.UserWallet }} </span>

      {% elif request.user.is_superuser %}
          <a href="{% url 'logout' %}">Logout</a>
          <br>
      <br>
         <span style="background-color: lightblue">Admin : {{ request.user.username }} </span>
      <br>
      <br>
          <a href="{% url 'returns' %}">To returns </a>

    <br>

    <br>
      <div>

       {% else %}
        <a href="{% url 'login' %}">Login</a>
        <br>
        <a href="{% url 'register' %}">Registration</a>
        <br>
        <br>

    {% endif %}



 {% if messages %}
<ul class="messages">
    {% for message in messages %}

    <li >{{ message }}
    </li>


    {% endfor %}
</ul>
{% endif %}
<br>
<div>
<br>
    {% for obj in object_list %}
    <div>


        {{ obj.title}} <br>
        {{ obj.description }} <br>
        Quaintity at warehouse: {{obj.quantity}}<br>

     {% if obj.picture %}
        <img src="{{ obj.picture.url }}" width="100" height="100">

{% endif %}
    <br>
    Price: {{ obj.price }}

{% if request.user.is_authenticated and not request.user.is_superuser %}



  <form  method="post" action="{% url 'purchase' obj.pk %}">
    {% csrf_token %}
    {{purchase_form }}
    <input type="hidden" name="product_id" value="{{ obj.id }}"><input type="hidden" name="customer_id" value="{{ request.user.id}}">
    <input type="submit" value="Buy">
       <br>

</form>

    {% endif %}

    <br>
    {% if request.user.is_superuser %}
    <form method="post" action="{% url 'update' obj.pk %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ create_form }}
    <input type="submit" value="Update">
</form>
    {% endif %}
    <br>
    <br>
    <br>
    <br>
    </div>
    {% endfor %}




{% if request.user.is_superuser %}
  <form method="post" action="{% url 'snus_create' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ create_form }}
    <input type="submit" value="Create">
</form>
{% endif %}
<br>
<br>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
        </div>
{% endblock %}

templates/login.html
{% extends 'main.html' %}

{% block content %}
<span>Wanna register? <a href="{% url 'register' %}">Sign Up</a></span>

<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Login">
</form>
{% endblock %}

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
</head>
<body>
<div>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/purchases.html
{% extends 'main.html' %}

{% block content %}
    {% if messages %}
<ul class="messages">
    {% for message in messages %}

    <li >{{ message }}
    </li>


    {% endfor %}
</ul>
{% endif %}
    <a href="{% url 'index' %}">To main page</a>
    <br>
    <br>
     {% for obj in object_list %}
    <div>


        Owner: {{ obj.customer}} <br>
        product: {{ obj.product }} <br>
        Purchase quaintity: {{obj.quantity}}<br>

     <form method="post" action="{% url 'return_snus' obj.pk %}">
    {% csrf_token %}
    {{return_purchase_form }}
    <input type="hidden" name="purchase_return_id" value="{{ obj.id }}">

    <input type="submit" value="Return">
       <br>

</form>
    <br>

     </div>
     {% endfor %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
        </div>

{% endblock %}

templates/register.html
{% extends 'main.html' %}

{% block content %}
<span>Already has account? <a href="{% url 'login' %}">Login</a></span>

<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Register">
</form>
{% endblock %}

templates/returns.html
{% extends 'main.html' %}
{% block content %}
    <span><h1 style="background-color: aqua">List of returns:</h1></span>
    <a href="{% url 'index' %}">To main page</a>
 {% for obj in returnpurchase_list %}
    <div>

        Owner:{{ obj.purchase_return.customer }}<br>
        Return:{{ obj.purchase_return.product}} <br>
        Return quantity:{{ obj.purchase_return.quantity}} <br>
    Return time: {{ obj.time_of_return }} <br>
<form method="post" action="{% url 'decline_return' obj.pk %}">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ obj.purchase_return }}"?</p>
    <input type="submit" value="Decline">
</form>

   <form method="post" action="{% url 'accept_return' obj.purchase_return.pk %}">
                            {% csrf_token %}


                            <input type="submit" value="Return">
                        </form>
    </div>
     <br>


 {% endfor %}
    <div class="pagination">
    <span class="step-links" style="background-color: aqua">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
        </div>


{% endblock %}